export type Locale = "en" | "zh-CN" | "zh-Hant";

const EN = {
  brandSubtitle: "Evidence-first IFC review",
  candidate: "Hosted MVP candidate",
  navStart: "Start",
  navAbout: "About & limits",
  navSource: "Source",
  eyebrow: "A Site-contained BIM Agent",
  heroTitle: "Review the evidence, not an AI opinion.",
  heroBody:
    "Upload a real IFC or use a synthetic sample. A bounded Agent inspects the model, invokes deterministic rules, critiques evidence completeness, and returns an auditable result.",
  boundary:
    "INFO-001 + Hong Kong Table B2 · Deterministic pre-check · Not statutory certification",
  tryMixed: "Try mixed review",
  uploadAction: "Upload my IFC",
  runtimeTitle: "One deployment, complete core path",
  runtimeUpload: "IFC input",
  runtimeUploadDetail: "Up to 50 MiB per IFC file",
  runtimeAgent: "Agent runtime",
  runtimeAgentDetail: "4 steps · 3 typed tools",
  runtimeVerdict: "Verdict authority",
  runtimeVerdictDetail: "Deterministic rules only",
  runtimeModel: "External inference",
  runtimeModelDetail: "None required",
  startTitle: "Start a bounded review",
  startBody:
    "Samples use the same parser, Agent, rules, evidence, storage, and export path as your upload.",
  samplesLabel: "Synthetic samples",
  sampleClean: "Clean model",
  sampleCleanDetail: "Complete explicit door information and clear-width evidence.",
  sampleMissing: "Missing information",
  sampleMissingDetail: "Required door properties are intentionally absent.",
  sampleMixed: "Mixed review",
  sampleMixedDetail: "PASS, FAIL, and REVIEW outcomes in one compact model.",
  sampleNarrow: "Narrow exit",
  sampleNarrowDetail: "An explicit exit clear width is below the Hong Kong Table B2 minimum.",
  sampleProxy: "Proxy width",
  sampleProxyDetail: "Nominal width exists, but reliable clear width is unavailable.",
  runSample: "Run sample",
  uploadTitle: "Your IFC",
  uploadBody: "The file is processed inside this Site runtime and is not sent to an external model.",
  chooseFile: "Choose IFC file",
  dropFile: "or drop one here",
  fileHint: ".ifc STEP · one or more files · maximum 50 MiB each",
  removeFile: "Remove selected file",
  objectiveLabel: "Review objective",
  optional: "Optional",
  objectivePlaceholder: "Example: Review this IFC using the enabled evidence-backed rules.",
  objectiveHint:
    "Up to 500 characters. Objectives may select supported work, but cannot change rules, thresholds, evidence, or verdicts.",
  runUpload: "Run Agent review",
  processingEyebrow: "Bounded run in progress",
  processingTitle: "The Site runtime is reviewing the IFC.",
  processingBody:
    "The request remains inside the deployed Site path. The verified Agent timeline will appear when the run reaches a typed terminal state.",
  processingUpload: "Upload validated",
  processingInspect: "Inspect model",
  processingReview: "Run rules",
  processingEvidence: "Assemble evidence",
  processingComplete: "Completed",
  processingReady: "Review complete. The result is ready to inspect.",
  viewResults: "View results",
  processingActive: "In progress",
  processingQueued: "Queued",
  processingWait: "Waiting for the runtime",
  errorTitle: "The review did not complete",
  requestLabel: "Request",
  retry: "Return to start",
  deletedTitle: "The retained run was deleted",
  deletedBody:
    "Its derived D1 documents and metadata are no longer retrievable. The raw IFC was never durably stored.",
  newReview: "New review",
  resultsEyebrow: "Canonical review workspace",
  resultsTitle: "Evidence-backed findings",
  expires: "Access expires",
  downloadJson: "Download Quick Check JSON",
  printReport: "Print Quick Check PDF",
  deleteRun: "Delete retained run",
  deleteConfirm:
    "Permanently delete this anonymous run and its derived results? This cannot be undone.",
  deleted: "Deleted",
  summaryTotal: "Total",
  summaryPass: "Pass",
  summaryFail: "Fail",
  summaryReview: "Review",
  findingsTitle: "Findings",
  filterAll: "All",
  filterPass: "Pass",
  filterFail: "Fail",
  filterReview: "Review",
  previous: "Previous",
  next: "Next",
  page: "Page",
  noFindings: "No findings match this filter.",
  selectFinding: "Select a finding to inspect its evidence.",
  applicability: "Applicability",
  entity: "Entity",
  modelEvidence: "Model evidence",
  ruleEvidence: "Rule evidence",
  explanation: "Bounded explanation",
  recommendation: "Recommended next step",
  sourcePath: "Source path",
  reliability: "Reliability",
  rawValue: "Raw",
  normalizedValue: "Normalized",
  ruleVersion: "Rule version",
  authority: "Authority",
  source: "Source",
  limitation: "Limitation",
  noObservation: "No direct observation was available.",
  agentTrace: "Agent execution trace",
  agentTraceBody:
    "Public lifecycle events only. Private chain-of-thought and raw IFC bytes are never exposed.",
  steps: "steps",
  toolCalls: "tool calls",
  stopReason: "stop reason",
  finalResponse: "Agent summary",
  aboutEyebrow: "About this MVP",
  aboutTitle: "Deliberately narrow, structurally extensible.",
  aboutBody:
    "This release proves a complete hosted Agent path for real IFC judgment. It does not pretend to solve every BIM discipline or every future hardware form.",
  aboutScopeTitle: "What it does now",
  aboutScopeBody:
    "Parses IFC2X3/IFC4 STEP, inventories model facts, runs INFO-001 and the selected Hong Kong Table B2 or demo width rule, preserves dual evidence, returns AgentRun/ReviewRun contracts, and exports canonical JSON.",
  aboutLimitTitle: "What it does not claim",
  aboutLimitBody:
    "No statutory certification, general BIM compliance, 3D viewer, Revit plugin, camera, ESP32, robotics, private-LAN access, user accounts, long-term memory, or external model inference.",
  aboutFutureTitle: "Why it can grow",
  aboutFutureBody:
    "Provider, connector, tool, capability, Agent, event, and result contracts remain platform-neutral. Future hardware profiles can expose only capabilities the device actually has.",
  privacyTitle: "Data & retention",
  privacyBody:
    "Raw IFC is processed in request memory. Derived runs use token-gated D1 storage. Exact-time retrieval expiry and request-driven deletion are implemented; unattended physical reconciliation must be verified before public real-file release.",
  footerBoundary: "Open source · deterministic verdicts · evidence before prose",
  restore: "Restoring the retained run from this browser session…",
  exportError: "The JSON export could not be downloaded.",
  deleteError: "The retained run could not be deleted.",
  invalidFile: "Choose .ifc files no larger than 50 MiB each.",
} as const;

const ZH_CN: Partial<Record<keyof typeof EN, string>> = {
  brandSubtitle: "证据优先的 IFC 审查",
  candidate: "托管 MVP 候选版",
  navStart: "开始",
  navAbout: "说明与边界",
  navSource: "源代码",
  eyebrow: "完整运行在站内的 BIM Agent",
  heroTitle: "审查证据，而不是相信 AI 意见。",
  heroBody:
    "上传真实 IFC，或直接使用合成样例。有界 Agent 会检查模型、调用确定性规则、复核证据完整性，并输出可审计结果。",
  boundary: "INFO-001 + 香港 Table B2 · 确定性预审 · 不构成法定认证",
  tryMixed: "体验混合样例",
  uploadAction: "上传我的 IFC",
  runtimeTitle: "一次部署，完整核心路径",
  runtimeUpload: "IFC 输入",
  runtimeUploadDetail: "每个 IFC 文件最大 50 MiB",
  runtimeAgent: "Agent 运行时",
  runtimeAgentDetail: "4 步 · 3 个类型化工具",
  runtimeVerdict: "判定权威",
  runtimeVerdictDetail: "仅确定性规则",
  runtimeModel: "外部推理",
  runtimeModelDetail: "默认不需要",
  startTitle: "开始一次有界审查",
  startBody: "样例与真实上传使用相同的解析器、Agent、规则、证据、存储和导出路径。",
  samplesLabel: "合成样例",
  sampleClean: "完整模型",
  sampleCleanDetail: "包含明确的门信息和可靠净宽证据。",
  sampleMissing: "信息缺失",
  sampleMissingDetail: "有意移除了部分必要门属性。",
  sampleMixed: "混合审查",
  sampleMixedDetail: "在一个小模型中同时包含 PASS、FAIL 与 REVIEW。",
  sampleNarrow: "出口过窄",
  sampleNarrowDetail: "明确的出口净宽低于演示阈值。",
  sampleProxy: "代理宽度",
  sampleProxyDetail: "有名义宽度，但缺少可靠净宽证据。",
  runSample: "运行样例",
  uploadTitle: "你的 IFC",
  uploadBody: "文件在当前 Site 运行时内处理，不会发送给外部模型。",
  chooseFile: "选择 IFC 文件",
  dropFile: "或拖放到这里",
  fileHint: ".ifc STEP · 可选择一个或多个文件 · 每个最大 50 MiB",
  removeFile: "移除所选文件",
  objectiveLabel: "审查目标",
  optional: "可选",
  objectivePlaceholder: "例如：使用已启用的证据规则审查这个 IFC。",
  objectiveHint: "最多 500 字。目标只能选择受支持的工作，不能更改规则、阈值、证据或判定。",
  runUpload: "运行 Agent 审查",
  processingEyebrow: "有界运行进行中",
  processingTitle: "Site 运行时正在审查 IFC。",
  processingBody: "请求始终位于当前部署路径内；到达类型化终态后，将显示经过验证的 Agent 时间线。",
  processingUpload: "上传已验证",
  processingInspect: "检查模型",
  processingReview: "运行规则",
  processingEvidence: "组装证据",
  processingComplete: "已完成",
  processingReady: "审查已完成，可以查看结果。",
  viewResults: "查看结果",
  processingActive: "进行中",
  processingQueued: "等待中",
  processingWait: "等待运行时返回",
  errorTitle: "审查未完成",
  requestLabel: "请求编号",
  retry: "返回开始页",
  deletedTitle: "留存运行已删除",
  deletedBody: "相关 D1 派生文档与元数据已无法读取；原始 IFC 从未被持久化。",
  newReview: "新建审查",
  resultsEyebrow: "权威审查工作区",
  resultsTitle: "有证据支撑的发现",
  expires: "访问到期",
  downloadJson: "下载 Quick Check JSON",
  printReport: "打印 Quick Check PDF",
  deleteRun: "删除留存运行",
  deleteConfirm: "永久删除本次匿名运行及其派生结果？此操作无法撤销。",
  deleted: "已删除",
  summaryTotal: "总计",
  summaryPass: "通过",
  summaryFail: "失败",
  summaryReview: "待复核",
  findingsTitle: "发现",
  filterAll: "全部",
  filterPass: "通过",
  filterFail: "失败",
  filterReview: "待复核",
  previous: "上一页",
  next: "下一页",
  page: "页",
  noFindings: "当前筛选条件下没有发现。",
  selectFinding: "请选择一条发现查看证据。",
  applicability: "适用性",
  entity: "构件",
  modelEvidence: "模型证据",
  ruleEvidence: "规则证据",
  explanation: "有界解释",
  recommendation: "建议下一步",
  sourcePath: "来源路径",
  reliability: "可靠性",
  rawValue: "原始值",
  normalizedValue: "归一化值",
  ruleVersion: "规则版本",
  authority: "权威类型",
  source: "来源",
  limitation: "限制",
  noObservation: "没有可用的直接观测。",
  agentTrace: "Agent 执行轨迹",
  agentTraceBody: "仅展示公开生命周期事件；不会公开私有思维链或原始 IFC。",
  steps: "步",
  toolCalls: "次工具调用",
  stopReason: "停止原因",
  finalResponse: "Agent 总结",
  aboutEyebrow: "关于本 MVP",
  aboutTitle: "当前范围刻意收束，后续结构保持开放。",
  aboutBody: "这一版证明了真实 IFC 判断的完整托管 Agent 路径，但不会假装已经覆盖所有 BIM 专业或硬件形态。",
  aboutScopeTitle: "现在能做什么",
  aboutScopeBody: "解析 IFC2X3/IFC4 STEP、盘点模型事实、执行 INFO-001 与所选香港 Table B2 或演示宽度规则、保留双证据、输出 AgentRun/ReviewRun，并导出权威 JSON。",
  aboutLimitTitle: "不做什么承诺",
  aboutLimitBody: "不提供法定认证、通用 BIM 合规、3D 查看器、Revit 插件、摄像头、ESP32、机器人、私有局域网访问、用户账户、长期记忆或外部模型推理。",
  aboutFutureTitle: "为什么还能扩展",
  aboutFutureBody: "Provider、Connector、工具、能力、Agent、事件和结果契约均保持平台中立；未来硬件只需公开设备实际具备的能力。",
  privacyTitle: "数据与留存",
  privacyBody: "原始 IFC 在请求内存中处理；派生运行采用令牌保护的 D1。精确读取过期和请求驱动删除已经实现；公开真实文件前仍需验证无人访问时的物理清理。",
  footerBoundary: "开源 · 确定性判定 · 证据先于文字",
  restore: "正在从当前浏览器会话恢复留存运行…",
  exportError: "无法下载 JSON 导出。",
  deleteError: "无法删除留存运行。",
  invalidFile: "请选择不超过 50 MiB 的 .ifc 文件；批量导入时超限文件会单独跳过。",
};

const ZH_HANT: Partial<Record<keyof typeof EN, string>> = {
  ...ZH_CN,
  brandSubtitle: "證據優先的 IFC 審查",
  candidate: "託管 MVP 候選版",
  navStart: "開始",
  navAbout: "說明與邊界",
  heroTitle: "審查證據，而不是相信 AI 意見。",
  heroBody: "上傳真實 IFC，或直接使用合成範例。有界 Agent 會檢查模型、呼叫確定性規則、覆核證據完整性，並輸出可審計結果。",
  tryMixed: "體驗混合範例",
  uploadAction: "上傳我的 IFC",
  startTitle: "開始一次有界審查",
  startBody: "範例與真實上傳使用相同的解析器、Agent、規則、證據、儲存和匯出路徑。",
  samplesLabel: "合成範例",
  sampleClean: "完整模型",
  sampleMissing: "資訊缺失",
  sampleMixed: "混合審查",
  sampleNarrow: "出口過窄",
  sampleProxy: "代理寬度",
  runSample: "執行範例",
  uploadTitle: "你的 IFC",
  chooseFile: "選擇 IFC 檔案",
  removeFile: "移除所選檔案",
  objectiveLabel: "審查目標",
  runUpload: "執行 Agent 審查",
  processingTitle: "Site 執行環境正在審查 IFC。",
  processingComplete: "已完成",
  processingReady: "審查已完成，可以查看結果。",
  viewResults: "查看結果",
  processingActive: "進行中",
  processingQueued: "等待中",
  requestLabel: "請求編號",
  resultsTitle: "有證據支撐的發現",
  downloadJson: "下載 Quick Check JSON",
  printReport: "列印 Quick Check PDF",
  deleteRun: "刪除留存執行",
  newReview: "新增審查",
  filterAll: "全部",
  filterPass: "通過",
  filterFail: "失敗",
  filterReview: "待覆核",
  modelEvidence: "模型證據",
  ruleEvidence: "規則證據",
  recommendation: "建議下一步",
  aboutTitle: "目前範圍刻意收束，後續結構保持開放。",
};

export type CopyKey = keyof typeof EN;

export function copy(locale: Locale, key: CopyKey): string {
  if (locale === "zh-CN") return ZH_CN[key] ?? EN[key];
  if (locale === "zh-Hant") return ZH_HANT[key] ?? EN[key];
  return EN[key];
}

export function detectLocale(language: string): Locale {
  const normalized = language.toLocaleLowerCase("en-US");
  if (/zh-(tw|hk|mo|hant)/.test(normalized)) return "zh-Hant";
  if (normalized.startsWith("zh")) return "zh-CN";
  return "en";
}
